-- Create database link 
create database link PRD.REGRESS.RDBMS.DEV.US.ORACLE.COM
  connect to SIMAT
  using '(DESCRIPTION =
    (ADDRESS_LIST =
        (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.2)(PORT = 1521))
    )
    (CONNECT_DATA =
        (SERVICE_NAME = MESWELLPRD)
    )
)';

--init AD_AUTHORITY
INSERT INTO AD_AUTHORITY
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   NAME, DESCRIPTION, AUTHORITY_TYPE, ACTION, EDITOR_RRN, PARENT_RRN, SEQ_NO,
   LABEL, LABEL_ZH)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, NAME, DESCRIPTION, MENU_TYPE, ACTION, AD_EDITOR_ID, PARENT_ID, SEQ_NO, LABEL, LABEL_ZH
  FROM   AD_MENU@PRD


--init AD_EDITOR
INSERT INTO AD_EDITOR
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   NAME, EDITOR_ID, PARAM1, PARAM2, PARAM3, PARAM4, PARAM5)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, NAME, EDITOR_ID, PARAM1, PARAM2, PARAM3, PARAM4, PARAM5
  FROM   AD_EDITOR@PRD


--init AD_FIELD
INSERT INTO AD_FIELD
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   NAME, DESCRIPTION, TABLE_RRN, TAB_RRN, SEQ_NO, DISPLAY_LENGTH, IS_DISPLAY,
   IS_KEY, IS_MAIN, IS_QUERY, IS_READONLY, IS_EDITABLE, IS_SAMELINE,
   IS_MANDATORY, IS_UPPER, IS_TABLE_FIELD, DISPLAY_TYPE, DATA_TYPE,
   MIN_VALUE, MAX_VALUE, REFERENCE_NAME, REFTABLE_RRN, USER_REFLIST_NAME,
   LABEL, LABEL_ZH)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, NAME, DESCRIPTION, AD_TABLE_ID, AD_TAB_ID, SEQ_NO, DISPLAY_LENGTH, IS_DISPLAY, IS_KEY, IS_MAIN, IS_QUERY, IS_READONLY, IS_EDITABLE, IS_SAMELINE, IS_MANDATORY, IS_UPPER, IS_TABLE_FIELD, DISPLAY_TYPE, DATA_TYPE, MIN_VALUE, MAX_VALUE, REFERENCE_NAME, AD_REF_TABLE_ID, AD_USER_REF_NAME, LABEL, LABEL_ZH
  FROM   AD_FIELD@PRD


--init AD_MESSAGE
INSERT INTO AD_MESSAGE
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   KEY, LANGUAGE, MESSAGE)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, KEY, LANGUAGE, MESSAGE
  FROM   AD_MESSAGE@PRD


--init AD_ORG
INSERT INTO AD_ORG
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   NAME, DESCRIPTION)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, NAME, DESCRIPTION
  FROM   AD_ORG@PRD


--init AD_TABLE
INSERT INTO AD_TABLE
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   NAME, DESCRIPTION, TABLE_NAME, IS_VIEW, MODEL_NAME, MODEL_CLASS,
   WHERE_CLAUSE, ORDER_BY_CLAUSE, LABEL, LABEL_ZH)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, NAME, DESCRIPTION, TABLE_NAME, IS_VIEW, MODEL_NAME, MODEL_CLASS, WHERE_CLAUSE, ORDER_BY_CLAUSE, LABEL, LABEL_ZH
  FROM   AD_TABLE@PRD


--init AD_TAB
INSERT INTO AD_TAB
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   NAME, DESCRIPTION, TABLE_RRN, SEQ_NO, GRID_Y, LABEL, LABEL_ZH)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, NAME, DESCRIPTION, AD_TABLE_ID, SEQ_NO, GRID_Y, LABEL, LABEL_ZH
  FROM   AD_TAB@PRD


--init AD_REFTABLE
INSERT INTO AD_REFTABLE
  (OBJECT_RRN, AD_ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED,
   UPDATED_BY, NAME, DESCRIPTION, TABLE_RRN, KEY_FIELD, VALUE_FIELD,
   WHERE_CLAUSE, ORDER_BY_CLAUSE)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, NAME, DESCRIPTION, AD_TABLE_ID, KEY_FIELD, VALUE_FIELD, WHERE_CLAUSE, ORDER_BY_CLAUSE
  FROM   AD_REF_TABLE@PRD


--init AD_REFLIST
INSERT INTO AD_REFLIST
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   REFERENCE_NAME, KEY, VALUE, SEQ_NO, DESCRIPTION)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, REFERENCE_NAME, NAME, VALUE, SEQ_NO, DESCRIPTION
  FROM   AD_REF_LIST@PRD


--init AD_USER
INSERT INTO AD_USER
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   USER_NAME, DESCRIPTION, PASSWORD, IS_INVALID, EMAIL, PHONE, PHONE2,
   DEPARTMENT, BIRTH_DAY, SEX, JOIN_TIME, DEFAULT_LANGUAGE, COMMENTS,
   PWD_CHANGED, PWD_LIFE, PWD_EXPIRY, LAST_LOGON, MENU_START,
   DEFAULT_ORG_RRN, IS_SHOW_LAUNCHER, DEFAULT_VIEW)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, USER_NAME, DESCRIPTION, PASSWORD, IS_INVALID, EMAIL, PHONE, PHONE2, DEPARTENT, BIRTH_DAY, SEX, JOIN_TIME, DEFAULT_LANGUAGE, COMMENTS, PWD_CHANGED, PWD_LIFE, PWD_EXPIRY, LAST_LOGON, MENU_START, DEFAULT_ORG_ID, IS_SHOW_LAUNCHER, DEFAULT_VIEW
  FROM   AD_USER@PRD


--init AD_USER_ORG
INSERT INTO AD_USER_ORG
  (USER_RRN, ORG_RRN)
  SELECT USER_OBJECT_ID, ORG_OBJECT_ID
  FROM   AD_USER_ORG@PRD


--init AD_USER_REFLIST
INSERT INTO AD_USER_REFLIST
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   REFERENCE_NAME, KEY, VALUE, SEQ_NO, DESCRIPTION)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, REFERENCE_NAME, NAME, VALUE, SEQ_NO, DESCRIPTION
  FROM   AD_USER_REF_LIST@PRD


--init AD_USERGROUP
INSERT INTO AD_USERGROUP
  (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY,
   USERGROUP_ID, DESCRIPTION)
  SELECT OBJECT_ID, AD_ORG_ID, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, USERGROUP_ID, DESCRIPTION
  FROM   AD_USERGROUP@PRD


--init AD_USERGROUP_AUTHORITY
INSERT INTO AD_USERGROUP_AUTHORITY
  (USERGROUP_RRN, AUTHORITY_RRN)
  SELECT USERGROUP_OBJECT_ID, MENU_OBJECT_ID
  FROM   AD_USERGROUP_AUTHORITY@PRD


--init AD_USERGROUP_USER
INSERT INTO AD_USERGROUP_USER
  (USERGROUP_RRN, USER_RRN)
  SELECT USERGROUP_OBJECT_ID, USER_OBJECT_ID
  FROM   AD_USERGROUP_USER@PRD

commit;