insert into ad_authority (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, AUTHORITY_TYPE, ACTION, EDITOR_RRN, PARENT_RRN, SEQ_NO, LABEL, LABEL_ZH)
values (700088, 0, 'Y', to_date('19-03-2012', 'dd-mm-yyyy'), 1, to_date('19-03-2012', 'dd-mm-yyyy'), 1, 0, 'INV.Storage.Lot', 'Storage Lot Query', 'F', 'E', 700089, 70, 99, 'Storage Lot Query', '入库批次查询');

insert into ad_table (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, TABLE_NAME, IS_VIEW, MODEL_NAME, MODEL_CLASS, WHERE_CLAUSE, ORDER_BY_CLAUSE, LABEL, LABEL_ZH, IS_VERTICAL, INIT_WHERE_CLAUSE)
values (26732794, 0, 'Y', to_date('20-03-2012 16:43:07', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('20-03-2012 16:43:07', 'dd-mm-yyyy hh24:mi:ss'), 1, 1, 'VINVLot', '分批入库查询', 'V_INV_LOT', 'N', 'InvLot', 'com.graly.erp.inv.model.InvLot', '', '', '', '入库分批查询', 'N', '');

insert into ad_editor (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, EDITOR_ID, PARAM1, PARAM2, PARAM3, PARAM4, PARAM5)
values (700089, 0, 'Y', to_date('21-03-2012', 'dd-mm-yyyy'), 1, to_date('21-03-2012', 'dd-mm-yyyy'), 1, 0, 'InvLotEditor', '', 'com.graly.erp.inv.lot.InvLotQueryEditor', '26732794', '', '', '', '');

insert into ad_field (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, TABLE_RRN, TAB_RRN, SEQ_NO, DISPLAY_LENGTH, IS_DISPLAY, IS_KEY, IS_MAIN, IS_QUERY, IS_READONLY, IS_EDITABLE, IS_SAMELINE, IS_MANDATORY, IS_UPPER, IS_TABLE_FIELD, DISPLAY_TYPE, DATA_TYPE, MIN_VALUE, MAX_VALUE, NAMING_RULE, REFERENCE_NAME, REFTABLE_RRN, USER_REFLIST_NAME, LABEL, LABEL_ZH, IS_PARENT, REFERENCE_RULE, IS_ADVANCE_QUERY)
values (26732820, 0, 'Y', to_date('21-03-2012 11:11:49', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('21-03-2012 11:11:49', 'dd-mm-yyyy hh24:mi:ss'), 1, 1, 'materialId', '物料号', 26732794, null, 1, null, 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N', '', 'text', 'string', '', '', '', '', null, '', '', '物料号', 'N', '', 'N');

insert into ad_field (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, TABLE_RRN, TAB_RRN, SEQ_NO, DISPLAY_LENGTH, IS_DISPLAY, IS_KEY, IS_MAIN, IS_QUERY, IS_READONLY, IS_EDITABLE, IS_SAMELINE, IS_MANDATORY, IS_UPPER, IS_TABLE_FIELD, DISPLAY_TYPE, DATA_TYPE, MIN_VALUE, MAX_VALUE, NAMING_RULE, REFERENCE_NAME, REFTABLE_RRN, USER_REFLIST_NAME, LABEL, LABEL_ZH, IS_PARENT, REFERENCE_RULE, IS_ADVANCE_QUERY)
values (26732821, 0, 'Y', to_date('21-03-2012 11:13:20', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('21-03-2012 11:13:57', 'dd-mm-yyyy hh24:mi:ss'), 1, 2, 'lotId', '批号', 26732794, null, 2, null, 'Y', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', '', '', '', '', '', '', '', null, '', '', '批号', 'N', '', 'N');

insert into ad_field (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, TABLE_RRN, TAB_RRN, SEQ_NO, DISPLAY_LENGTH, IS_DISPLAY, IS_KEY, IS_MAIN, IS_QUERY, IS_READONLY, IS_EDITABLE, IS_SAMELINE, IS_MANDATORY, IS_UPPER, IS_TABLE_FIELD, DISPLAY_TYPE, DATA_TYPE, MIN_VALUE, MAX_VALUE, NAMING_RULE, REFERENCE_NAME, REFTABLE_RRN, USER_REFLIST_NAME, LABEL, LABEL_ZH, IS_PARENT, REFERENCE_RULE, IS_ADVANCE_QUERY)
values (26732822, 0, 'Y', to_date('21-03-2012 11:14:32', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('21-03-2012 11:17:27', 'dd-mm-yyyy hh24:mi:ss'), 1, 2, 'docId', '入库单号', 26732794, null, 3, null, 'Y', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', '', '', '', '', '', '', '', null, '', '', '入库单号', 'N', '', 'N');

insert into ad_field (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, TABLE_RRN, TAB_RRN, SEQ_NO, DISPLAY_LENGTH, IS_DISPLAY, IS_KEY, IS_MAIN, IS_QUERY, IS_READONLY, IS_EDITABLE, IS_SAMELINE, IS_MANDATORY, IS_UPPER, IS_TABLE_FIELD, DISPLAY_TYPE, DATA_TYPE, MIN_VALUE, MAX_VALUE, NAMING_RULE, REFERENCE_NAME, REFTABLE_RRN, USER_REFLIST_NAME, LABEL, LABEL_ZH, IS_PARENT, REFERENCE_RULE, IS_ADVANCE_QUERY)
values (26732823, 0, 'Y', to_date('21-03-2012 11:15:14', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('21-03-2012 11:17:08', 'dd-mm-yyyy hh24:mi:ss'), 1, 3, 'dateCreated', '入库时间', 26732794, null, 5, null, 'Y', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', '', '', '', '', '', '', '', null, '', '', '入库时间', 'N', '', 'N');

insert into ad_field (OBJECT_RRN, ORG_RRN, IS_ACTIVE, CREATED, CREATED_BY, UPDATED, UPDATED_BY, LOCK_VERSION, NAME, DESCRIPTION, TABLE_RRN, TAB_RRN, SEQ_NO, DISPLAY_LENGTH, IS_DISPLAY, IS_KEY, IS_MAIN, IS_QUERY, IS_READONLY, IS_EDITABLE, IS_SAMELINE, IS_MANDATORY, IS_UPPER, IS_TABLE_FIELD, DISPLAY_TYPE, DATA_TYPE, MIN_VALUE, MAX_VALUE, NAMING_RULE, REFERENCE_NAME, REFTABLE_RRN, USER_REFLIST_NAME, LABEL, LABEL_ZH, IS_PARENT, REFERENCE_RULE, IS_ADVANCE_QUERY)
values (26732824, 0, 'Y', to_date('21-03-2012 11:16:43', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('21-03-2012 11:17:17', 'dd-mm-yyyy hh24:mi:ss'), 1, 2, 'qtyMovement', '入库数量', 26732794, null, 4, null, 'Y', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', '', '', '', '', '', '', '', null, '', '', '入库数量', 'N', '', 'N');

